version: '3'

volumes:
  certbotdata:

networks:
  backend-network:
    driver: bridge

services:
  nginx:
    image: nginx:stable
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./options/nginx:/etc/nginx/conf.d
      - ./options/letsencrypt:/etc/letsencrypt
      - certbotdata:/var/www/certbot
    networks:
      - backend-network
    ports:
      - 80:80
      - 443:443
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./options/letsencrypt:/etc/letsencrypt
      - certbotdata:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  planetiler:
    image: ghcr.io/onthegomap/planetiler:latest
    volumes:
      - './data:/data'
    command: --only-download --force --area=portugal --output=portugal.pmtiles

  tileserver:
    build: ./tileserver
    restart: unless-stopped
    volumes:
      - './data:/data'
    networks:
      - backend-network
